/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_CG_menu (void);
GtkWidget* create_CG_Insc (void);
GtkWidget* create_CG_Modif (void);
GtkWidget* create_CG_supp (void);
GtkWidget* create_CG_Aff (void);
